### ISSUE TITLE
Possibility of displaying time in 24 format.

### ISSUE THREAD

**Issue by SergeySergeevitch** [3rob3/ImmichFrame#1]
Possibility of displaying time in 24 format. And also hide the clock and date through the settings file.

**Comment by 3rob3** [comment]
I added support for this in latest release.

**Comment by SergeySergeevitch** [comment]
Thank you! My language is not very... This is cool. And now it works as expected!
I'm also worried about screen burn-in around the numbers. I think that dates and times should be made wandering?

**Comment by SergeySergeevitch** [comment]
And I use Win64 - it works beautifully)

**Comment by 3rob3** [comment]
> I'm also worried about screen burn-in around the numbers. I think that dates and times should be made wandering?
I don't think that would be an issue, the values are always changing. My Google Home has been running like this for years and I haven't noticed any burn-in. I suppose you could either disable these, or change the font size periodically if you were really concerned.

**Comment by 3rob3** [comment]
> Thank you! My language is not very... This is cool. And now it works as expected! I'm also worried about screen burn-in around the numbers. I think that dates and times should be made wandering?

I don't think that would be an issue, the values are always changing. My Google Home has been running like this for years and I haven't noticed any burn-in. I suppose you could either disable these, or change the font size periodically if you were really concerned.
