### ISSUE TITLE
Change weather provider to MET.no

### ISSUE THREAD

**Issue by agdamsbo** [3rob3/ImmichFrame#102]
### Description

Have you considered implementing other weather sources like to met.no, which offer free forecasts through their quite extensive api service (https://api.met.no/weatherapi/)?

### Use Case

This wonderful frame app would be even more useful with a free weather data service.

### Pre-Submission Checklist

- [X] This is a feature request and not a bug report

- [X] I have checked for related issues and checked the documentation

**Comment by JW-CH** [comment]
Just FYI: The current weather-api is free. You just need to have an API-Key.

For your request: I assume that you are talking about the location forecast (https://api.met.no/weatherapi/locationforecast/2.0/documentation). It looks like the met.no API is lacking some features (weather as text, translations, current weather). I am not sure if this is something worth implementing.

CC @3rob3

**Comment by agdamsbo** [comment]
> Just FYI: The current weather-api is free. You just need to have an API-Key.
> 
> For your request: I assume that you are talking about the location forecast (https://api.met.no/weatherapi/locationforecast/2.0/documentation). It looks like the met.no API is lacking some features (weather as text, translations, current weather). I am not sure if this is something worth implementing.
> 
> CC @3rob3

Ah. I see. I have met.no weather data on my HomeAssistant instance and i runs well with translations, but, if nothing extra is gained, no reason to spend time on it!
