### ISSUE TITLE
Configure scaling method (scale to fit vs. cover)

### ISSUE THREAD

**Issue by OliverLippertVw** [3rob3/ImmichFrame#103]
### Description

Users should be able to controll whether pictures that doesn't have the same ratio as the screen are scaled down to fit (+ that nice blur background effect) or if they should be scaled up to cover the full screen.

### Use Case

Picuter and Display have different ratio. (e.g. 4:3 vs. 16:9)

### Pre-Submission Checklist

- [X] This is a feature request and not a bug report

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
The current implementation uses the default Stretch value of Uniform: 
image is scaled to fit within the container while preserving its aspect ratio. The entire image is visible, and there may be empty space if the aspect ratios differ. 

I assume you want to option of UniformToFill':
image is scaled to fill the entire container while preserving its aspect ratio, but parts of the image may be clipped if the aspect ratios differ.
