### ISSUE TITLE
Don't throw exception when no settings are found, just show settings page.

### ISSUE THREAD

**Issue by 3rob3** [3rob3/ImmichFrame#104]
### Version

1.0.7.0

### Deployment Method

All

### Description

From a new user who downloaded from the play store, seeing an error right away would probably scare them.

### Reproduction

start app with no settings

### Expectations

Just show Settings page

### Pre-Submission Checklist

- [X] This is a bug report and not a feature request

- [X] I have provided all of the required information to reproduce the bug (config, logs, etc.)

- [X] I have checked for related issues and checked the documentation

**Comment by JW-CH** [comment]
Working on a welcome page, #107 will solve this
