### ISSUE TITLE
Is it possible to support memories?

### ISSUE THREAD

**Issue by vspaziani** [3rob3/ImmichFrame#12]
It would be nice to cycle through memories as shown on the web. I have looked at the API could you possibly use the "getMemoryLane" function? I don't actually know C#.

What a great project!

**Comment by JW-CH** [comment]
@vspaziani and only show memories? What is your Use-Case? I am interested in your thoughts, why the memories would be valuable to have.

**Comment by vspaziani** [comment]
My use case is that I would like the frame to cycle through previous photos from this day historically. Currently when you log in on the web, there is a bar of historical photos from previous years. In reading the API I think it is exposed through that call. This would not be random photos but specific photos taken in previous years.

**Comment by 3rob3** [comment]
Google Home displays do this and I do enjoy that. I can see adding this, difficulty is how to implement. Personally I don’t have enough photos so it would only cycle through a handful each day, which is kind of useless. Others may have tons, and others in between. Maybe something like every 5 minutes display a random photo from memories if enabled?

**Comment by vspaziani** [comment]
Yes, I’m on the other end where I have a lot of photos. about 20-30 each day in memories. I don’t care if it is random, but that could work. I just wanted it to cycle through the pictures from this day historically.

**Comment by JW-CH** [comment]
Oh, so you only would like to see memories and not albums? If you only have one memory, only one image is displayed right?

**Comment by vspaziani** [comment]
> Oh, so you only would like to see memories and not albums? If you only have one memory, only one image is displayed right?

That is correct. Only display the photos from this day. Maybe a splash screen or message when no memories?

**Comment by JW-CH** [comment]
@vspaziani hope this helps :)
