### ISSUE TITLE
DNS Failure

### ISSUE THREAD

**Issue by TheITRx** [3rob3/ImmichFrame#126]
### Version

v1.0.9.0

### Deployment Method

Android TV

### Description

Every morning, I see this in my screen. The app crashes overnight and spits out this error. 

![image](https://github.com/user-attachments/assets/dc693e1f-b36f-49e0-b6d1-4105ac69446e)

### Reproduction

n/a

### Pre-Submission Checklist

- [X] This is a bug report and not a feature request

- [X] I have provided all of the required information to reproduce the bug (config, logs, etc.)

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
Might want to update your image, Your URL is showing further down (8 lines below marked out one).

**Comment by TheITRx** [comment]
> Might want to update your image, Your URL is showing further down (8 lines below marked out one).

Thanks!

**Comment by 3rob3** [comment]
Have you tried enabling UnattendedMode? Do you have Screensaver enabled? For some reason your device is losing network connection but the app is still alive/running.

**Comment by TheITRx** [comment]
> Have you tried enabling UnattendedMode? 

That's off. But I just turned it on. Let's see how it goes tomorrow. 

> Do you have Screensaver enabled?

No, I just fire up the app. I haveit run 24/7 on a chromecast for a portable LCD screen in my living room. 

> For some reason your device is losing network connection but the app is still alive/running.

That's what I suspect. When does the app query the API? On each refresh? or each picture? But it only happens during the night.

**Comment by TheITRx** [comment]
hmm. case closed.. my router is intermittently rebooting during the dawn.. seeing it in the logs. I think that is the culprit. Thanks!

**Comment by 3rob3** [comment]
Oh good, well, for me at least :). I'd still try the unattended mode. It may be enough to suppress the error messages and continue on when network comes back.
