### ISSUE TITLE
ImmichFrame

### ISSUE THREAD

**Issue by crobibero** [3rob3/ImmichFrame#128]
### Version

1.0.11.0

### Deployment Method

Play Store

### Description

ImmichFrame app is not available for AndroidTV devices, only Phone, Chromebook, and Tablet.

### Reproduction

Attempt to install the ImmichFrame app on an AndroidTV device

### Pre-Submission Checklist

- [X] This is a bug report and not a feature request

- [X] I have provided all of the required information to reproduce the bug (config, logs, etc.)

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
Correct, Google would not approve it for Android TV so I gave up trying. You will need to sideload it.

**Comment by crobibero** [comment]
That's a shame, may want to think about utilizing https://go.aftvnews.com/ to make AndroidTV download simpler like SmartTube does
