### ISSUE TITLE
ImmichFrame doesn't start on Amazon devices - crashes immediately

### ISSUE THREAD

**Issue by deddc23efb** [3rob3/ImmichFrame#129]
### Version

1.0.12.0

### Deployment Method

Amazon fire HD 10 Amazon degoogled Android

### Description

The application doesn't attempts to start up and then exits immediately.  Apparently this is common in Android apps that have a dependency on Google specific features (Chromecast?)  
Amazon fire devices are inexpensive and common enough.  It would be great to see this tool supported on that platform.

### Reproduction

Install latest APK on an amazon fire.  start it up and watch it crash.

### Expectations

The app should run normally.

### Configuration

```xml
No config available - the app doesn`t get that far.
```

### Logs

```shell
I have no logs from the app for this.
```

### Pre-Submission Checklist

- [X] This is a bug report and not a feature request

- [X] I have provided all of the required information to reproduce the bug (config, logs, etc.)

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
There are no Google specific features (I'm running it on a Firestick 4k). Others are successfully running it on Fire tablets. You aren't the first to report an issue on Fire HD 10, but we were never able to figure out a pattern. What generation is it? Without having a device it is very difficult to solve this as Amazon quit supplying emulators for their devices.

**Comment by deddc23efb** [comment]
I have  few Amazon devices of different generations and size.  I'll test on those as well when I get a chance.  The specific one that I encountered the issue on is:
Fire HD 10 (9th generation) running FireOS 7.3.2.9
I do NOT have the Googleplay store installed - that sometimes drags along the infrastructure to support google features.

**Comment by 3rob3** [comment]
I don't have Play store installed on my FireTV either, so it has nothing to do with that. Were you able to test on any other devices?

**Comment by deddc23efb** [comment]
Thanks for the reminder.
Amazon Fire HD 10 (11th generation), Fire OS 7.3.3.0, release 1.0.12.0 Signed APK, starts normally presents config page, GOOD
Amazon Fire HD 10 (11th generation), Fire OS 7.3.3.0,  release 1.0.12.0 Unsigned APK, won't install APK, NEUTRAL
Amazon Fire 7 (7th generation), fireOS 5.6.9.0, release 1.0.12.0 Signed APK installs, starts and hangs on a black screen with white stripe doesn't function, BAD
Amazon Fire 7 (7th generation), fireOS 5.6.9.0, release 1.0.12.0 Unsigned APK, refuses to install complains of problem parsing package, NEUTRAL
Amazon Fire HD 8(7th generation) FireOS 5.7.1.0, release 1.0.12.0 Signed APK, starts normally and presents config page,GOOD
Amazon Fire HD 8(7th generation) FireOS 5.7.1.0, release 1.0.12.0 Unsigned APK, refuses to install complains of problem parsing package, NEUTRAL
Amazon Fire HD 10 (9th generation), Fire OS 7.3.2.9, release 1.0.12.0 Signed APK, starts see gray screen exits to "desktop",BAD
Amazon Fire HD 10 (9th generation), Fire OS 7.3.2.9, release 1.0.12.0 Unsigned APK, refuses to install jumps to App not Installed, NEUTRAL

**Comment by deddc23efb** [comment]
Two more hardware devices to add. Both of the devices required updating so I tested the APK on each iteration as I upgraded.
Based on the results I'm seeing, the pattern is that the FireOS version and Generation of the  Amazon Fire HD 10 and maybe the 8 is not the issue.  

The only modern device (the 5 inch tablet excluded) that has a problem is an HD 10 (gen 9).  Given that a Gen 7 has no issues I'm suspecting that the problem is an interaction with installed software more than the device itself.  At some point I'll reset my Gen 9 and see if the problem goes away.

More data below:

Amazon Fire HD 10 (11th generation), Fire OS 7.3.1.8, release 1.0.12.0 Signed APK, starts normally and presents config page, GOOD
Amazon Fire HD 10 (11th generation), Fire OS 7.3.2.7, release 1.0.12.0 Signed APK, starts normally and presents config page, GOOD
Amazon Fire HD 10 (11th generation), Fire OS 7.3.2.8, release 1.0.12.0 Signed APK, starts normally and presents config page, GOOD
Amazon Fire HD 10 (11th generation), Fire OS 7.3.2.8, release 1.0.12.0 Signed APK, starts normally and presents config page, GOOD
Amazon Fire HD 10 (11th generation), Fire OS 7.3.2.9, release 1.0.12.0 Signed APK, starts normally and presents config page, GOOD
Amazon Fire HD 10 (7Th generation), Fire OS 5.6.9.0, release 1.0.12.0 Signed APK, starts normally and presents config page, GOOD
Amazon Fire HD 10 (7Th generation), Fire OS 5.7.0.0, release 1.0.12.0 Signed APK, starts normally and presents config page, GOOD
Amazon Fire HD 10 (7Th generation), Fire OS 5.7.1.0, release 1.0.12.0 Signed APK, starts normally and presents config page, GOOD

**Comment by 3rob3** [comment]
Can this be closed then? Not sure what else to do here.

**Comment by deddc23efb** [comment]
Yes please close it. Thank you. I'm successfully running immichframe on an Amazon Fire HD 10 Gen 11 and it's working well.  Thank you for the software.

**Comment by 3rob3** [comment]
Did we ever figure out the issue? Was it a app loader?

**Comment by deddc23efb** [comment]
> Did we ever figure out the issue? Was it a app loader?

No, sadly.  I uninstalled Nova Launcher and a few other apps. I'm not ready to wipe that machine to try it out from clean.  I'll try again when I finally do that on the Gen 9 Tablet.
