### ISSUE TITLE
Immich frame as a screen saver for Mac OS

### ISSUE THREAD

**Issue by frachop** [3rob3/ImmichFrame#138]
### Description

It would be awesome to be able to use Immich Frame as a MAC OS Screen saver 

### Use Case

It would be awesome to be able to use Immich Frame as a MAC OS Screen saver 

### Pre-Submission Checklist

- [X] This is a feature request and not a bug report

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
This was just requested recently. MacOS has some special requirements for screensavers. For one they have to be written in native code, therefore we would need to create a wrapper in Swift or similar. If you know anybody who can contribute with that we would happily accept, but it's probably out of scope for us.
