### ISSUE TITLE
Install instructions?

### ISSUE THREAD

**Issue by alternativesurfer** [3rob3/ImmichFrame#15]
I plan to install this on a Pi, but for now was going to test on Windows.

I am running the executable but nothing happens. Thinking wheel spins for a minute or two and then nothing.
What am I missing?

**Comment by JW-CH** [comment]
Did you rename the Settings.example.xml to Settings.xml

**Comment by 3rob3** [comment]
Be sure to fill out all your settings, and rename it like JW-CH mentions. If you are not using albums delete the inner nodes, i.e:
<Albums>		
</Albums>

**Comment by JW-CH** [comment]
Feel free to post your Settings.xml here, make sure to remove/hide your sensitive data like apikey and domain etc.

But I agree, a better HowTo or instructions is much needed.
