### ISSUE TITLE
Feature: Filter photos by face

### ISSUE THREAD

**Issue by Me-Mr** [3rob3/ImmichFrame#22]
Hi! Thanks for the amazing app!

I just wanted to suggest a feature: I think it would be useful to be able to specify faces to only show photos from.

**Comment by 3rob3** [comment]
I have this mostly done, will review with @JW-CH tomorrow.

**Comment by Me-Mr** [comment]
Awesome!

**Comment by JW-CH** [comment]
> I have this mostly done, will review with @JW-CH tomorrow.

If you open a PR, I can review it. Note that I am also rebuilding how the calls are made with OpenApi. So we have to test it again :)

**Comment by 3rob3** [comment]
This is done, we just need to figure out the other PR first.
