### ISSUE TITLE
Feature: echo show 5 

### ISSUE THREAD

**Issue by vednolacni** [3rob3/ImmichFrame#27]
Hello! Thanks for the amazing app!!

I just wanted to suggest a feature: I woud like to use echo show 5 for slideshow.

**Comment by 3rob3** [comment]
hmm, do Echo's support adding apps? Or side-loading apps? I have no experience with them but seems unlikely.

**Comment by 3rob3** [comment]
Android app is out, doubt it will be compatible with Exho Show but probably as close as we are going to get. Closing.
