### ISSUE TITLE
run as a webservice?

### ISSUE THREAD

**Issue by Symbiot78** [3rob3/ImmichFrame#30]
Can it be done? 
that it runs on a server, or even better, in a docker container, and I would be able to point a browser to the container and show the slideshow?

**Comment by 3rob3** [comment]
Yes Avalonia (which this project is based on) supports web assemblies. I have considered this as well, so will spend some time on it this week to see if it seems worthwhile.

**Comment by JW-CH** [comment]
> Can it be done? that it runs on a server, or even better, in a docker container, and I would be able to point a browser to the container and show the slideshow?

Immich has a slideshow functionality. You might want to look into that.

**Comment by 3rob3** [comment]
I am going to close due to Immich web already containing this functionality.

**Comment by Symbiot78** [comment]
@3rob3 - terribly sorry I didn't reply earlier.
I asked this question at the immich github(or was is reddit) and was told to look at the immichframe.
Maybe I didn't explain it properly the first time 'round.

What I am looking for is the possibility to create a URL that will start a screensaver/picture slideshow.

the goal is to have a screensaver/picture slideshow that I can call via home assistant on my dashboard when it's not active.

so if immichframe ran as a webservice in a docker for instance I could call the corresponding IP for immichframe and a path to start the slideshow configured in immichframe.

Immich itself does not have the option (according to devs).
