### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by comfreak89** [3rob3/ImmichFrame#42]
1) Setting to set a time in seconds, how long a transition from one picture to another
2) Setting to be able to configure to show 2 vertical pictures at the same time next to each other

**Comment by 3rob3** [comment]
1. do you mean time how long the transition takes (if so we also discussed doing this)? Or how long a picture is shown before switching (if so this already exists with 'Interval')?
2. A few people have also requested this. We may wait until this is implemented in Immich. See here: https://discord.com/channels/979116623879368755/1217843270244372480/1222960071223545947

**Comment by comfreak89** [comment]
1. Yes, the time how long the transition takes.
2. Alright!

**Comment by 3rob3** [comment]
creating a new issue for second request
