### ISSUE TITLE
Feature: Display Location

### ISSUE THREAD

**Issue by xeonixo** [3rob3/ImmichFrame#43]
Hi! Really nice project!

Could you add the Possibility to show the City and Country above the Image-Date?

Maybe with a language option - so for Example:
English: Cologne, Germany
German: Köln, Deutschland

**Comment by 3rob3** [comment]
This would be fairly easy to add. My only concern is running out of screen real estate.

**Comment by JW-CH** [comment]
Crazy, I was just about to implement this again :D
I just looked at the immich api to see if the data would be available.

**Comment by JW-CH** [comment]
Is 'Phare du Cap Fréhel' the album's title?

**Comment by 3rob3** [comment]
Looks like album names to me. 
City and Country are available under getAssetInfo-exifInfo. What I'm not sure of is what language it would be in.

**Comment by JW-CH** [comment]
![image](https://github.com/3rob3/ImmichFrame/assets/17313367/a31fa4d4-8177-44df-800d-97eb062762c4)
Small WIP, sorry for the widescreen haha

**Comment by JW-CH** [comment]
> Looks like album names to me. City and Country are available under getAssetInfo-exifInfo. What I'm not sure of is what language it would be in.

I looked that up, it takes the exif data that was stored in the database. This is completely handled by immich.

**Comment by JW-CH** [comment]
Btw. currently there is no language option. Immich just returns the English name.

**Comment by 3rob3** [comment]
> Btw. currently there is no language option. Immich just returns the English name.

That's what I was afraid of....bummer. Maybe they will add system wide language support someday. Haven't looked but would assume that's on their roadmap.

**Comment by JW-CH** [comment]
> > Btw. currently there is no language option. Immich just returns the English name.
> 
> That's what I was afraid of....bummer. Maybe they will add system wide language support someday. Haven't looked but would assume that's on their roadmap.

https://discord.com/channels/979116623879368755/1071165397228855327/1237060732106051635

**Comment by sigalou** [comment]
"Phare du Cap Fréhel" 
It’s the location. The GPS coordinates are translated by the Google Maps API, all you need is a token. For the time, day date, we also put a format, I just put Y to only have the year

![image](https://github.com/3rob3/ImmichFrame/assets/26350534/29132e50-e40e-4e75-97d7-46de795687f3)
