### ISSUE TITLE
Feature: Weather language

### ISSUE THREAD

**Issue by xeonixo** [3rob3/ImmichFrame#44]
Is it possible to add a language option for weather?

**Comment by 3rob3** [comment]
Possible? Sure, but not real easy. We basically use lookup table to get a text description of a WMO weather code. This table is currently hard coded. To do this we would need to either:
1. Translate the description after lookup using an API (I am not seeing anything free or doesn't require an API key)
2. Find a WMO interpreter that supports many languages. Same as above (not seeing anything free or doesn't require an API key)
3. Manually translate them all (not fun but probably doable). I guess there are only ~30 though
