### ISSUE TITLE
Invalid WeatherUnits "celcius"

### ISSUE THREAD

**Issue by l4rm4nd** [3rob3/ImmichFrame#49]
Using the release binary for Windows and the following in `Settings.xml`:

````
<!--The temperature units. either celcius or fahrenheit-->
<WeatherUnits>celcius</WeatherUnits>
````

![image](https://github.com/3rob3/ImmichFrame/assets/21357789/a717be10-bcb2-4f9b-a43d-269df63d8966)

**Comment by JW-CH** [comment]
This way a typo of mine, can you set it to celsius? This should be already fixed.

**Comment by l4rm4nd** [comment]
Works, thanks!
