### ISSUE TITLE
Error: Value cannot be Null (Parameter 's')

### ISSUE THREAD

**Issue by xeonixo** [3rob3/ImmichFrame#53]
Hi, I've got multiple times the error 

```
Value cannot be Null (Parameter 's')

```

After pressing ok it's working again... but my frame has no input 

![image](https://github.com/3rob3/ImmichFrame/assets/90346961/81e7afb7-5d59-4152-ad77-6bb495fda57a)

**Comment by 3rob3** [comment]
Can you paste in the XML contents? You can obfuscate your server url and api key.

**Comment by xeonixo** [comment]
i already checked for some typo... nothing sus found.

`<Settings>
        <ImmichServerUrl>https://pixel.barner.cloud</ImmichServerUrl>
        <ApiKey>#########</ApiKey>
        
        <Interval>8</Interval>
        
        <DownloadImages>false</DownloadImages>
        
        <ShowMemories>false</ShowMemories>
        
        <RenewImagesDuration>20</RenewImagesDuration>
        
        <ShowClock>true</ShowClock>
        <ClockFontSize>48</ClockFontSize>
        
        <ClockFormat>HH:mm</ClockFormat>
        
        <ShowPhotoDate>true</ShowPhotoDate>
        <PhotoDateFontSize>36</PhotoDateFontSize>
        
        <PhotoDateFormat>dd.MM.yyyy</PhotoDateFormat>
        
        <ShowImageDesc>true</ShowImageDesc>
        <ImageDescFontSize>36</ImageDescFontSize>
        
        <ShowWeather>true</ShowWeather>
        <WeatherFontSize>12</WeatherFontSize>
        
        <WeatherUnits>celsius</WeatherUnits>
        
        <WeatherLatLong>40.7128,74.0060</WeatherLatLong>
</Settings>
`

**Comment by 3rob3** [comment]
I edited you post to remove your URL since it is public.
XML seems fine. Can you provide a little more detail? When does the error occur (i.e. after first photo, or does it run awhile then this happens)? What do you mean by "my frame has no input", no more photos are shown after the error? Just to rule it out, can you enter your server's IP:port (i.e. http://192.168.0.100:2283) instead of the public URL and verify same behavior?

**Comment by xeonixo** [comment]
> Can you provide a little more detail? When does the error occur (i.e. after first photo, or does it run awhile then this happens)?
it varies. sometimes after the first few pictures, sometimes after hours

> What do you mean by "my frame has no input", no more photos are shown after the error? 
Sorry for the confusion, my Raspberry Pi does not normally have a mouse and keyboard. Therefore, I cannot simply click "ok".

> Just to rule it out, can you enter your server's IP:port (i.e. http://192.168.0.100:2283) instead of the public URL and verify same behavior?
Unfortunately, my DMZ/reverse proxy network is not directly accessible for the Raspberry Pi.

**Comment by JW-CH** [comment]
I had this problem also, but could not replicate it. I think this was gone after the rework I did. Maybe wait for the next release?

**Comment by xeonixo** [comment]
Tried with using the ip of my immich instance directly. The error remains random.

I changed to an album only, before i used my whole gallery. Maybe it's an issue with archived images?
