### ISSUE TITLE
Feature: Interactive control

### ISSUE THREAD

**Issue by AlmightyFrog** [3rob3/ImmichFrame#58]
I know it is meant to be used as a picture frame.

But would it be possible to e.g. if you use it at a tablet (Linux or maybe Android in future) to show your pictures to others that they can interact like following?
- freeze slide show to current frame to look more in detail at it
- go back to last picture
- go further to next picture

Might be touch or cursor keys on keyboard maybe.

**Comment by 3rob3** [comment]
Seems like a neat idea. I have been in this situation with Google Nest Hub where I wanted to show someone a pic but they weren't in the room so I kept needing to swipe back until they were there.

**Comment by abe-101** [comment]
@AlmightyFrog you may missed it in the readme
but you can click on the left hand side of the screen to go back to the previous picture

**Comment by abe-101** [comment]
But +1 for keyboard support (arrows)

**Comment by 3rob3** [comment]
> @AlmightyFrog you may missed it in the readme but you can click on the left hand side of the screen to go back to the previous picture

Good point! I didn't even catch that they may have missed that.
