### ISSUE TITLE
Feature: Add Exit button to settings page

### ISSUE THREAD

**Issue by 3rob3** [3rob3/ImmichFrame#61]
If valid settings are not entered, there is no way to exit the application.

**Comment by abe-101** [comment]
Why
U cant force quit the application?

**Comment by 3rob3** [comment]
You can, just not a very graceful solution. Say you started the app for first time, but forgot to copy your api key, it forces you into settings but there is no way out without entering valid settings. This solves that scenario.

**Comment by abe-101** [comment]
Oh I missed that

Cancel just removes the new settings

And if needed there's a quit button to shut down the app
