### ISSUE TITLE
Getting Segmentation Fault when trying to launch (Pi Zero)

### ISSUE THREAD

**Issue by Sharnyaaa** [3rob3/ImmichFrame#64]
Hey,

I love the idea of this! I have an old pi zero sitting around and want to use it as a digital photo frame that reads off Immich, I got the linux-arm release but when I try to launch it I get an error that just says "Segmentation fault" any idea where I should look to fix it?

**Comment by 3rob3** [comment]
I'm not 100%, but pretty sure it is due to insufficient memory on these lower end devices (I have seen it on Pi 2B as well, though it still works). There is some more info here:
https://linuxconfig.org/solving-the-segmentation-fault-error-on-linux

**Comment by 3rob3** [comment]
@JW-CH  , you have a Pi 3 right? Do you see segmentation faults on that device?

**Comment by JW-CH** [comment]
I have not seen this issue on my Pi3 when I tested some time ago. I'll check again if there is an issue with the newest Version.

**Comment by JW-CH** [comment]
Sorry for the late reply, it seems to be working fine on my Pi3.

**Comment by 3rob3** [comment]
Thanks. Guess I’ll update the readme to say Pi 3 and greater recommended. Guessing it is a memory issue.

**Comment by Sharnyaaa** [comment]
Thanks for looking into it for me! :)

**Comment by malcolmrigg** [comment]
Is there any way I can try and debug this? I'd like to get it running on a Pi Zero too - I've increased the size of the swap file to 2GB and still get this error, but I guess it could be looking for "real" memory?

It fails instantly too, which to me doesn't immediately scream memory issue, though that's a complete guess.

**Comment by malcolmrigg** [comment]
Ok, a little googling found this:
https://www.petecodes.co.uk/install-and-use-microsoft-dot-net-7-with-the-raspberry-pi/

"It’s important to note that .NET 7 will only work on an AMR32v7 processor or above… So that’s a Raspberry Pi 2 and upwards…"

Looks like it's a non-starter!

**Comment by malcolmrigg** [comment]
> Ah, that's it then. Nice work and thanks for updating us! From your link it looks like a Pi Zero 2W will work?

Yes, think so in theory, though I don't have one handy to test. I may end buying one if I don't have something else suitable already, if I do I'll let you know how it goes.
