### ISSUE TITLE
Win64:Malware-gen ??

### ISSUE THREAD

**Issue by sigalou** [3rob3/ImmichFrame#69]
### Version

V1.0.1.0Win-x64

### Deployment Method

Desktop Win-x64

### Description

I wanted to install the Windows version but Avast tells me there is Maware in the code?! Exact ?

![image](https://github.com/3rob3/ImmichFrame/assets/26350534/ce7c27d9-ce5f-4fd5-a657-72ce6c2026e7)

### Reproduction

Download : https://github.com/3rob3/ImmichFrame/releases/download/v1.0.1.0/ImmichFrame-v1.0.1.0-win-x64.zip

### Pre-Submission Checklist

- [x] This is a bug report and not a feature request

- [X] I have provided all of the required information to reproduce the bug (config, logs, etc.)

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
I'm guessing this is because it is not signed. I don't use Avast, but Windows also gives a warning you have to ignore. There is no malware, the code is open source so you can look for yourself. We don't even create the builds locally, Github does.

**Comment by sigalou** [comment]
Thank you for your prompt response. I suspected it, but it was mainly to inform you of this message.
