### ISSUE TITLE
Store API-Key instead of credentials

### ISSUE THREAD

**Issue by JW-CH** [3rob3/ImmichFrame#7]
Storing the username and password does not really sound good to me. Why are you not using a API-Key from immich? API-Keys can easily be created and removed and do not contain sensitive data.

**Comment by 3rob3** [comment]
I will look into this, the API documentation doesn't have a lot of info about using the API Key. Do you know if it is the same as "accessToken"? 
Funny enough I had this same thought this morning before I got out of bed, and woke up to this message :)

**Comment by JW-CH** [comment]
Hey, I just saw your reply. I thought I'd do this on my own if it is OK.

**Comment by 3rob3** [comment]
Awesome! Great idea with the settings.xml.....you have no idea how many times I pushed mine with my credentials intact.....ugh. As you can probably tell I am new at Git.

**Comment by JW-CH** [comment]
> Awesome! Great idea with the settings.xml.....you have no idea how many times I pushed mine with my credentials intact.....ugh. As you can probably tell I am new at Git.

Ugh in that case you really need to watch out! People can see the Password you have used! Have a look at this: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

I am active on the immich discord (pinged you) maybe we could discuss that there :)

**Comment by 3rob3** [comment]
I merged your changes and created new builds. Thanks again for your help! I will probably post to reddit, what is your reddit username so I can credit you?

**Comment by JW-CH** [comment]
Thank you. I am not really using Reddit so it is totally fine, no need to mention :)
