### ISSUE TITLE
Kodi / OSMC integration?

### ISSUE THREAD

**Issue by lmgithu** [3rob3/ImmichFrame#70]
### Version

latest

### Deployment Method

Linux

### Description

Hi, I love this project, would you be able to release it as a kodi plugin as well? I think you have everything ready already, but many people run kodi based media systems and a release for that would help increasing adoption. 

### Reproduction

-

### Expectations

A Kodi release :D

### Configuration

```xml
-
```

### Logs

```shell
-
```

### Pre-Submission Checklist

- [X] This is a bug report and not a feature request

- [X] I have provided all of the required information to reproduce the bug (config, logs, etc.)

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
I think that is out of scope for this project, sorry. You should be able to create a script for Kodi to be to launch a standalone binary (this app), I'm pretty sure I did that years ago when I used to use Kodi.

**Comment by JW-CH** [comment]
Maybe something we could/will address with the web version?
