### ISSUE TITLE
Android support for older versions?

### ISSUE THREAD

**Issue by pjft** [3rob3/ImmichFrame#71]
Hi.

I'm assuming that this is the issue - otherwise I'm finding that opening the APK file gives me an APK parsing error.

Still, the context is that I'd like to be able to repurpose an older Android tablet for this project, as it's a good way to give them a fresh lease of life.

In my case, I have an old Kindle Fire 7 tablet, that from what I can tell runs Android 5.1. Any way we could build the APK file to support that old a version, or is it a lost cause?

Thanks for putting this together, and apologies for the trouble.

**Comment by 3rob3** [comment]
According to Avalonia documentation this should be possible (though I have no idea what the performance would be like). The minimum API level Avalonia supports is 21, which is Android 5.0. I will try to create a test build for you to try and will reply back here when I get around to it.

Also worth noting that another user can't get it to work on his Fire HD 8 Plus tablet, and I haven't been able to reproduce so haven't been able to figure out what could be causing the crash.

**Comment by pjft** [comment]
Hi @3rob3 . Thank you for the reply, and for entertaining this experiment. I'm happy to run the test build on my end and report back. For what it's worth, I'm happy to run a build that creates a text log that I can share with you, if it's of interest.

Thank you, and no urgency whatsoever here - just let me know when there's something for me to test and I'll report back as well.

Have a great weekend!

**Comment by 3rob3** [comment]
I changed minSdkVersion to 21, it built and ran on Android 5.0 emulator. I will still get you a test build to try before next release.

**Comment by pjft** [comment]
Cool, thank you!
