### ISSUE TITLE
Feature: Adjustable margins

### ISSUE THREAD

**Issue by 3rob3** [3rob3/ImmichFrame#74]
Add settings value for Margin. This can allow fine tuning for display alignment or adjust for overscan

**Comment by xeonixo** [comment]
Hi! Sorry for requesting here again.

I have a new project and need to change the aspect-ratio with the margin. currently the original aspect ratio will be kept. the "frame" over my screen has a classic 4:3 ratio but my screen is 16:9, so I could not fit the frame perfectly.

Also, did you have some progress by changing the background black? It would shine less trough my first build ^^

Would be really lovely, if you could check on this again!

**Comment by 3rob3** [comment]
I don't know why but I can't see this message on GitHub so I'm replying
here, hopefully you get it. The background follows your system theme, so if
you have Dark mode enabled it will be black. For the other question, I
don't think I am understanding. What is not working?

**Comment by xeonixo** [comment]
Sorry for confusion, I deleted my comment, because everything is working. I was just too stupid for the right order of margin values.
Am 4. Aug. 2024, 23:50 +0200 schrieb 3rob3 ***@***.***>:

**Comment by 3rob3** [comment]
haha, glad it's working.
