### ISSUE TITLE
Use Language setting for PhotoDateFormat

### ISSUE THREAD

**Issue by bo0tzz** [3rob3/ImmichFrame#76]
### Description

When using a PhotoDateFormat such as `dd MMMM yyyy`, use the configured Language to localize the month name.

### Use Case

Displaying the month name in different languages

### Pre-Submission Checklist

- [X] This is a feature request and not a bug report

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
I would assume the same for dddd also?

**Comment by bo0tzz** [comment]
Probably, MMMM is just the one I happened to run into.
