### ISSUE TITLE
Play Videos instead of displaying Thumbnail

### ISSUE THREAD

**Issue by dercavendar1** [3rob3/ImmichFrame#77]
### Description

It would be nice if the application could play the videos stored rather than just staying on the thumbnail of the video.  

### Use Case

It would be nice if the application could play the videos stored rather than just staying on the thumbnail of the video.  

### Details

It would also be a benefit if the settings.xml could allow you to universally mute or leave audio enabled.  

### Pre-Submission Checklist

- [X] This is a feature request and not a bug report

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
Marking this as closed by #111. We don't play videos still but at least will not show the thumbnail of them anymore.
