### ISSUE TITLE
Create an album on immich server "Recent ImmichFrame Photos" 

### ISSUE THREAD

**Issue by 3rob3** [3rob3/ImmichFrame#80]
### Description

via bo0tzz on Discord:
I just had an interesting idea, I wonder what y'all think of it. When you have a frame going somewhere, a picture might pass by that you want to do something with, and depending on the setup the frame might not have a way to interact with it. How about having an option to put the latest n pictures into an album automatically, so you can easily pull them up from another device?

### Use Case

Easily access/Interact/do something with a photo you recently saw displayed on your phot frame.

### Pre-Submission Checklist

- [X] This is a feature request and not a bug report

- [X] I have checked for related issues and checked the documentation

**Comment by xeonixo** [comment]
Great idea! Sometimes I saw pictures, wich could be removed 😄
