### ISSUE TITLE
Filter trashed and archived images

### ISSUE THREAD

**Issue by Bendabir** [3rob3/ImmichFrame#81]
### Description

It seems that the endpoint used to get random assets can return trashed or archived assets. It would be nice to add options to filter out such assets. I believe there is no other option than requesting a new asset when one is being filtered out.

### Use Case

If assets are deleted or archived, I wouldn't like them to be displayed in the slideshow;

### Details

I can try to come up with a patch but I've never done C# before 😅 

### Pre-Submission Checklist

- [X] This is a feature request and not a bug report
- [X] I have checked for related issues and checked the documentation

PS : Really cool project ! Thanks for sharing.

**Comment by 3rob3** [comment]
This seems like an Immich PR really. Although maybe it’s best we stop using this endpoint and do the randomizing ourself. GetRandom currently is not including image some other exif also. There is an Immich PR for that already.

**Comment by Bendabir** [comment]
Yeah, I agree it should be on the Immich side. I was more thinking about a temporary workaround. Good to know that there is a PR ongoing. I guess we can close this issue then.

**Comment by JW-CH** [comment]
> This seems like an Immich issue really. Although maybe it’s best we stop using this endpoint and do the randomizing ourself. GetRandom currently is also not including some other exif data. There is an Immich PR for that already.

This is already released, btw.

For the trashed/archieved assets: I will test it again if this is still an issue with the newest version and update this comment if it is.

**Comment by JW-CH** [comment]
Ok, so I tested it again and noticed that trashed assets do NOT get returned. Archieved ones get returned. This is probably a bug in immich. Can we close this issue?

**Comment by Bendabir** [comment]
Yes, definitely. I'll try to patch on the Immich side if time permits. Thanks a lot !
