### ISSUE TITLE
ImmichURL setting bad regex parsing

### ISSUE THREAD

**Issue by desmond206x** [3rob3/ImmichFrame#83]
### Version

1.0.2.0

### Deployment Method

Desktop

### Description

I struggled way too much with the input of the immich url with the combination of an unclear api key with l and I in it.

So as a first time user of immich-frame I didn't know in which format the url should be input. 
With /api or without, just the url or do I need the port ...? 

Use this test data for testing with regex101.com

```
http://immich.de
https://immich.de
http://immich.de/
https://immich.de/
http://immich.de/api
https://immich.de/api
http://immich.de:2283
https://immich.de:2083
http://immich.de:2283/
https://immich.de:2083/
http://immich.de:2283/api
https://immich.de:2083/api

http://immichlocal
https://immichlocal
http://immichlocal/
https://immichlocal/
http://immichlocal/api
https://immichlocal/api
http://immichlocal:2283
https://immichlocal:2283
http://immichlocal:2283/
https://immichlocal:2283/
http://immichlocal:2283/api
https://immichlocal:2283/api

http://immichlocal.local
https://immichlocal.local
http://immichlocal.local/api
https://immichlocal.local/api
http://immichlocal.local:2283
https://immichlocal.local:2283
http://immichlocal.local:2283/api
https://immichlocal.local:2283/api

http://192.168.178.2
https://192.168.178.2
http://192.168.178.2/
https://192.168.178.2/
http://192.168.178.2/api
https://192.168.178.2/api
http://192.168.178.2:2283
https://192.168.178.2:2283
http://192.168.178.2:2283/
https://192.168.178.2:2283/
http://192.168.178.2:2283/api
https://192.168.178.2:2283/api
```

The best case would be, if all of these are accepted and parsed correctly. Maybe reject the /api ones, but there should be a error message which helps.

### Reproduction

https://regex101.com/r/mw03TU/1

### Expectations

All given inputs should be parsed correctly

### Configuration

```xml
Clean settings on first start
```

### Pre-Submission Checklist

- [X] This is a bug report and not a feature request

- [X] I have provided all of the required information to reproduce the bug (config, logs, etc.)

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
We already do regex matching on the URL:
                    if (!Regex.IsMatch(url, @"^(https?:\/\/)?(([a-zA-Z0-9\.\-_]+(\.[a-zA-Z]{2,})+)|(\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b))(\:\d{1,5})?$"))
                        throw new SettingsNotValidException($"Value of '{SettingsValue.Key}' is not valid. (' {value} ')");

We could add checking for "/API" but not sure what more can be done. People use all sorts of methods for access. You should enter whatever you would enter from a web browser.

**Comment by desmond206x** [comment]
Exactly. Just look at the regex101 link.
Only 12 of 48 cases are accepted currently. 

You do not tell the user what is wrong with the link. This is bad ux. 
For me I tried over and over again with a combination of only "immich" as my local dns name. But the regex checks for a ".". I didn't know this and thought my api key is wrong or I need to add /api to the url.

**Comment by 3rob3** [comment]
I replaced the regex with Uri.TryCreate, which is a little more robust.
