### ISSUE TITLE
Message Boxes unreadable on light theme

### ISSUE THREAD

**Issue by desmond206x** [3rob3/ImmichFrame#84]
### Version

1.0.2.0

### Deployment Method

Desktop, Android

### Description

The message boxes, opened by the settings view, are unreadable on devices (desktop and android).
For android it helped to switch to dark theme, but on my desktop pc it is always black on black.

![image](https://github.com/3rob3/ImmichFrame/assets/833191/4adc939f-4075-45a2-a6a3-43dd8a50cdc0)

![image](https://github.com/3rob3/ImmichFrame/assets/833191/b37b8cfb-1e85-4941-9e22-80c964d6aa17)

### Reproduction

Enter some invalid data into the settings dialog

### Pre-Submission Checklist

- [X] This is a bug report and not a feature request

- [X] I have provided all of the required information to reproduce the bug (config, logs, etc.)

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
Oh jeez....your right! How has this never come up before? grr....

**Comment by 3rob3** [comment]
The MessageBox control we're using seems to not be switching to Light Mode correctly. I can force the app to use always use Dark Mode, and that solves the issue. Obviously not ideal.
