### ISSUE TITLE
Adjust image time with GMT offset

### ISSUE THREAD

**Issue by GitPuffy** [3rob3/ImmichFrame#85]
### Description

Would it be possible for ImmichFrame to adjust the time presented to local time.  My images are stored in GMT/UTC.
I understand that I am able to adjust the formatting of the date and time of the images shown which I have done but I still need to do the math in my head of subtracting (or adding I suppose) from GMT to calculate local time.  Thank you.

### Use Case

Show the time the image was recorded in local time of the device displaying the photo.

### Pre-Submission Checklist

- [X] This is a feature request and not a bug report

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
What does immich show on web for this? Is it adjusting GMT->Local?

**Comment by GitPuffy** [comment]
Immich (not ImmichFrame) shows the picture timestamp as the time it was taken and also includes the time zone offset.  For example, May 28 2024 Tue, 5:44PM GMT-06:00.  The time the picture was taken was actually 5:44PM local time.  ImmichFrame shows the image as 11:44PM.  It is adding in the timezone offset even though I am in the same timezone the picture was taken.  Both are -6:00 hours.

**Comment by 3rob3** [comment]
We are currently using 'fileCreatedAt ', I think if we used 'localDateTime' it would handle this automatically:
https://immich.app/docs/api/get-asset-info

Any objections?

**Comment by 3rob3** [comment]
Closing, will be in next release.

**Comment by GitPuffy** [comment]
This is working great now.  Thank you for the adjustment.

**Comment by 3rob3** [comment]
Thanks for the follow up!
