### ISSUE TITLE
Receiving a 404 API error with Immich version 1.106.2

### ISSUE THREAD

**Issue by GitPuffy** [3rob3/ImmichFrame#87]
### Version

v1.0.3.0

### Deployment Method

Desktop

### Description

Receiving a 404 error related to API when starting Immich Frame.

I found this issue for Immich created earlier today related to breaking problems with API:
https://github.com/immich-app/immich/issues/10143

I do not know if your program will need to be refactored with API changes.

### Reproduction

Run Immich Frame against version 1.106.2 of Immich

### Pre-Submission Checklist

- [X] This is a bug report and not a feature request

- [X] I have provided all of the required information to reproduce the bug (config, logs, etc.)

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
Yes, we have a PR for it already but thanks for reporting. Should be released soon.

**Comment by JW-CH** [comment]
#86
