### ISSUE TITLE
Possible to set a specific album

### ISSUE THREAD

**Issue by kruemelro** [3rob3/ImmichFrame#9]
It would be very usefull to set a specific album instead of the whole library.

So i could share an album with my wife and set it as source in the ImmichFrame. With this, my wife and myself are able to define the pictures of the frame.

**Comment by 3rob3** [comment]
This keeps getting asked, but is more complicated than you would think. See here for latest answer:
https://www.reddit.com/r/immich/comments/1asfv5g/immichframe_v1003_slideshow_photo_frame_for_immich/

**Comment by JW-CH** [comment]
Immich v1.95.1 released 🎉 I will take a look into the api/search changes that were made and see if this is possible.

**Comment by kruemelro** [comment]
Hi,
i don't know the changes of the v1.95. But i had a look at the api documentation.
A possible solution could be the [get-album-info](https://immich.app/docs/api/get-album-info). With this you get an array of all asset IDs related to a specific album. 

Then the result from the getRandom could be checked against the array. If its a match then display the picture, elso do another getRandom call. Sure not the the most beautiful solution.

**Comment by JW-CH** [comment]
I get what you are saying, but if an album contains just 10 pictures and the whole server has like thousands, the API would get spammed with getRandom requests. If get-album-info returns an array of asset-IDs, the app could do the random calls by itself. I'll have a look into that.

**Comment by kruemelro** [comment]
yes, thats what i have meaned with "not the most beautiful solution" ;-)

Implement the random function und just pull the asset ids would be a great solution! Thanks for your work

**Comment by 3rob3** [comment]
I started looking into this last night. Nothing has changed API-wise that I can tell that would affect this request. My original implementation of this app did not use the API at all, it just indexed all the files in the library folder and I did my own collection and randomizing of them. I think what is needed is combining both approaches.
- If the user has an album(s) defined, use getAlbumInfo to get back an array of assets for that album
- If no album defined use getAllAssets to get an array of all assets (possibly include isFavorite here which is another request)
We could then use Random (like I did in original implementation) to get a random element from the list and display it. We would also have to refresh the assets periodically (daily?) to be able to show newly added photos. We would also have to filter out videos from the list. 

Also thinking at this point a Settings screen may be needed as we may have outgrown the manually entered XML approach. Maybe this is the next step and just get it working first?

**Comment by kruemelro** [comment]
Please stay with the xml config approach. 
A settings screen brings the requirement of a touchscreen or other input devices. With the config file we could run the app headless with just a display and raspberry

**Comment by 3rob3** [comment]
good point

**Comment by JW-CH** [comment]
I am currently working on an album implementation. I'll create a PR later today :) Currently refactoring some code as well :)

**Comment by JW-CH** [comment]
PR is here :)

**Comment by 3rob3** [comment]
> PR is here :)

Thanks again for your work, changes and refactoring look good! 
- I'm at work so can't test (plus I don't use albums), how is the performance?
- Do you see any issue with GetAlbumAssetIds returning a video asset? Or does "format=JPEG" in the ImageUrl handle that scenario?

**Comment by JW-CH** [comment]
Let's continue the discussion on the PR :)
