### ISSUE TITLE
AndroidTV Remote doesn't work in settings

### ISSUE THREAD

**Issue by crobibero** [3rob3/ImmichFrame#91]
### Version

v1.0.5.0

### Deployment Method

Chromecast with Google TV

### Description

Opening the app on first install opens a settings view that is impossible to navigate without mouse/keyboard.

I was able to work around this by using an ADB mouse and keyboard app on my phone, but if I enter settings after configuration I am stuck in the settings view as back doesn't close the view.

### Reproduction

1. Install app on AndroidTV
2. Attempt to use remote to navigate

### Expectations

The user should be able to navigate settings using the dpad on the remote

### Pre-Submission Checklist

- [X] This is a bug report and not a feature request

- [X] I have provided all of the required information to reproduce the bug (config, logs, etc.)

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
Yeah, this is a known issue/limitation. I just figured most would use a mouse/keyboard for initial setup since entering API keys would totally suck using a remote control. I'll see if I can make it workable though.

**Comment by crobibero** [comment]
Requiring a mouse and keyboard for initial setup is probably fine, but getting stuck in the settings view isn't ideal since the only way to get back is to force-close the app or restart the device

**Comment by 3rob3** [comment]
agreed
