### ISSUE TITLE
Freezes Raspberry Pi

### ISSUE THREAD

**Issue by fallingb41** [3rob3/ImmichFrame#94]
### Version

1.0.5.0

### Deployment Method

Raspberry Pi

### Description

When running on a Raspberry Pi Zero 2 W or Pi 3 B, Immich Frame will freeze and the Pi becomes unresponsive after 15~60 minutes. On a Pi 5 (4GB memory), it runs fine. I'm thinking not enough memory or the GPU can't handle it. Any suggestions or a way to help it run on older models?

### Reproduction

Unzip in the home directory.  Set preferences to pull a specific Album.  Run the executable.

### Expectations

Run without freezing.

### Pre-Submission Checklist

- [X] This is a bug report and not a feature request

- [X] I have provided all of the required information to reproduce the bug (config, logs, etc.)

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
Pi 3 should be fine. One of the contributors runs it on that. Yes we have heard issues with it on Pi 2's (my tests on mine have been fine, just has jerky transitions but never crashes). I would suggest:
- run Raspberry Pi OS (not sure of others but reports indicate issues with DietPi). Maybe try the non GUI version too.
- try reducing TransitionDuration. You won't get the nice fade in/out but should be easier on GPU and/or memory. Try values less than 1.

**Comment by fallingb41** [comment]
After reimaging and setting the TransitionDuration to 0.5, it did much better but still ended up freezing a few hours later. I'm going to try fan cooling the Pi to see if that helps.

**Comment by 3rob3** [comment]
> After reimaging and setting the TransitionDuration to 0.5, it did much better but still ended up freezing a few hours later. I'm going to try fan cooling the Pi 3B to see if that helps.

Any update? Can I close this?

**Comment by fallingb41** [comment]
> > After reimaging and setting the TransitionDuration to 0.5, it did much better but still ended up freezing a few hours later. I'm going to try fan cooling the Pi 3B to see if that helps.
> 
> Any update? Can I close this?

Sorry!
I wasn't able to get it to work. It just keeps freezing. I'm going to try something else and come back to this with a faster Pi in the future.

**Comment by 3rob3** [comment]
> > > After reimaging and setting the TransitionDuration to 0.5, it did much better but still ended up freezing a few hours later. I'm going to try fan cooling the Pi 3B to see if that helps.
> > 
> > 
> > Any update? Can I close this?
> 
> Sorry! I wasn't able to get it to work. It just keeps freezing. I'm going to try something else and come back to this with a faster Pi in the future.

Maybe try the next release (hopefully this week). It is a pretty large update (new framework and Avalonia versions).

**Comment by ScottFries** [comment]
Another data point on this: I was having the same issue with my Pi Zero 2W looking up within an hour. After reducing interval and transition times (to a 0.25 transition every 30s) I was able to run for 10-16hr before the device froze and saw full swap usage (normal given Raspberry Pi OS on this device), high RAM usage (normally hovers between 200-300MB, was close to 400MB of 426MB), and massive CPU usage from /usr/bin/rpi-connectd.

Currently running another test where I've disabled the desktop and expanded swap (from 200MB to 2GB) with a 1s transition every 10s and have been running for 6hrs now without issue. Will update if this changes, but currently it does seem like this is just a case of memory exhaustion that's easy enough to resolve if you're looking to only deploy ImmichFrame to the device. I'm also working on changing to Raspberry Pi OS Lite to further reduce resource consumption.

**Comment by 3rob3** [comment]
Good news, thanks for following up. I kinda suspected it was a RAM issue. On my Pi2 tests I was running lite OS with nothing else installed.

**Comment by fallingb41** [comment]
This was a present for my parents so I don't have the Pi anymore. But I hope to try again in the future.
I did run it with full Pi OS so maybe Lite will be better. But even on the Pi 3B with 1GB RAM, it was freezing after a few hours (sometimes within 15 minutes).
