### ISSUE TITLE
Exclude album feature

### ISSUE THREAD

**Issue by adambomb1011** [3rob3/ImmichFrame#96]
### Description

Instead of albums to include, can we also exclude albums

### Use Case

I have tons of albums, with only about 5 that I don't want to include. Rather than listing out which albums to include. Can I just exclude the 5?

### Details

I have tons of albums, with only about 5 that I don't want to include. Rather than listing out which albums to include. Can I just exclude the 5?

### Pre-Submission Checklist

- [X] This is a feature request and not a bug report

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
This is a bigger change than you would think. Short reason is we use the GUID for Albums and/or People to build a list of assets we then randomize. If we only had an album exclusion GUID we wouldn't have the other GUID's to get assets from.

Could you just create a dedicated ImmichFrame user, and only share the albums you want with them? Not ideal but that should accomplish what you want.

**Comment by JW-CH** [comment]
I think you still could use the random endpoint and then check if the asset is in an excluded album. Should not be too hard if you ask me.

**Comment by 3rob3** [comment]
closed by #111
