### ISSUE TITLE
More settings for weather display

### ISSUE THREAD

**Issue by TomokoK** [3rob3/ImmichFrame#98]
### Description

I am requesting a feature which would allow the user to tweak how weather stats are displayed.

### Use Case

Being able to hide or show parts of the weather statistics as needed would improve customizability and reduce screen clutter (if customized accordingly).

### Details

I think being able to tweak what weather stats are displayed would be beneficial. For example, I would like to hide the weather location as the lat/long are hard coded and I'm not likely going to forget which city I live in. I would also rather have the temperature readout rounded to a whole number as having one decimal place isn't really meaningful. Being able to pick and choose which information is displayed would be helpful.

### Pre-Submission Checklist

- [X] This is a feature request and not a bug report

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
I agree with you and would also like weather with no decimal (this is helpful for Celsius people mostly), and to not show city. I’m trying to not make settings and more cluttered though so need to come up with a clever solution.

**Comment by ScottFries** [comment]
> I agree with you and would also like weather with no decimal (this is helpful for Celsius people mostly), and to not show city. I’m trying to not make settings any more cluttered though so need to come up with a clever solution.

Have you put any thought in to how you might be looking to refactor the settings for the app?

**Comment by 3rob3** [comment]
Having GitHub build issues currently so that’s top priority. I’m leaning toward just removing city. Like you said it’s hard coded so we know where we are. May need a poll or something to see if anybody needs/wants decimal places in temperature (I personally don’t).

**Comment by agdamsbo** [comment]
Hi! Ive just found this app. Wow! Good job! Have you considered implementing other weather sources like to met.no, which offer free forecasts through their quite extensive api service (https://api.met.no/weatherapi/)

**Comment by 3rob3** [comment]
> Hi! Ive just found this app. Wow! Good job! Have you considered implementing other weather sources like to met.no, which offer free forecasts through their quite extensive api service (https://api.met.no/weatherapi/)

Wow, never heard of that one. Love that no API key is needed, it's free and government run, and the service looks great. Would you mind creating a new issue for this request? That way it doesn't get lost/forgotten when this one closes.
