### ISSUE TITLE
Cannot use most recent version. Executable not working and settings file appears to be incorrect.

### ISSUE THREAD

**Issue by vspaziani** [3rob3/ImmichFrame#99]
### Version

1.0.7.0

### Deployment Method

Raspberry PI 5, unzipping

### Description

When I download and unzip the release for my raspberry PI, I am unable to use the files that are included with the release. The executable is not able to be ran since it does not have to correct rights. When I add the execute flag to it with Chmod, I still cannot run the file. I had to revert to Version 1.0.5.0 in order to obtain a functional package.

I did not see any mention of breaking changes when reviewing the release notes but I do note that the expanded zip has a 'JSON' file for version 1.0.7.0 and in 1.0.5.0 it is an xml for the settings. All the previous versions that I have had prior to this update were all xml for the settings.

### Reproduction

Download version 1.0.7.0 from releases [Arm 64 version](https://github.com/3rob3/ImmichFrame/releases/download/v1.0.7.0/ImmichFrame-v1.0.7.0-linux-arm64.zip)

expand

change relevant settings in JSON file

Execute application

### Expectations

Executable to work after settings were set

### Configuration

```xml
... this file does not exist (as 'settings.xml'). As mentioned in issues, it is settings.JSON
```

### Logs

```shell
NA
```

### Pre-Submission Checklist

- [X] This is a bug report and not a feature request

- [X] I have provided all of the required information to reproduce the bug (config, logs, etc.)

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
Settings.xml was replaced with Settings.json. This was done to simplify and consolidate code with Android but is functionally the same. 

I just downloaded the linux-arm64 from releases, transferred it to my Pi5, and it is working fine. What OS are you using, and is it Full or lite version? Are you seeing an error message?

**Comment by vspaziani** [comment]
Thanks for the followup.  Sorry I thought I mentioned that. Though with your help I dug a little deeper and figured it out.

I am running Ubuntu 24.04 LTS, the desktop version.

When I expand the zip for ImmichFrame-v1.0.7.0-linux-arm64 I only see two files: Immich_Frame  and Settings.example.json 

after I copy and modify the settings.json, when I click on "Immich_Frame" I do receive an error stating 

> **Could not Display software**  There is no app installed for "executable" files

Steps to resolve for me:

1. Expand Zip File
2. Copy Settings.example.json to Settings.json
3. modify Settings.json to suit my environment
4. Remove unused options from Settings.json (`"Albums": [""],` &    `"People": [""],` in my file
6. right click on Immich_Frame, select properties from context menu.
7. at the bottom, select 'Execute as Program' to TRUE and click OK
8. Right Click on Immich_Frame and select 'Open with..."
9.  choose 'Run Software' and ensure that aways use for this file type is set to TRUE

**Comment by 3rob3** [comment]
oh jeez, I will add that to Readme. Thanks for following up with how to fix it!
